import type { SkillId } from '../game/encounter/encounterTypes'

export const statusIconMap: Record<string, string> = {
  stable: '/status-icons/stable.svg',
  enraged: '/status-icons/enraged.svg',
  fortified: '/status-icons/fortified.svg',
  weakened: '/status-icons/weakened.svg',
  lurking: '/status-icons/lurking.svg',
  stunned: '/status-icons/stunned.svg',
  taunted: '/status-icons/taunted.svg',
  'mass-taunt': '/status-icons/mass-taunt.svg',
  haste: '/status-icons/haste.svg',
  sundered: '/status-icons/sundered.svg',
  evasion: '/status-icons/evasion.svg',
  silenced: '/status-icons/silenced.svg',
  guarded: '/status-icons/guarded.svg',
  'enrage-song': '/status-icons/enrage-song.svg',
  snared: '/status-icons/snared.svg',
  shieldWall: '/status-icons/shield-wall.svg',
  'vanguard-oath': '/status-icons/vanguard-oath.svg',
  'ember-aegis': '/status-icons/ember-aegis.svg',
  'heat-haze': '/status-icons/heat-haze.svg',
  'battle-seal': '/status-icons/battle-seal.svg',
  suppression: '/status-icons/heat-haze.svg',
  'formation-break': '/status-icons/sundered.svg',
  'chaos-volley': '/status-icons/enrage-song.svg',
  dislike_affix_pic: '/status-icons/dislike.svg',
  oldGrudge_affix_pic: '/status-icons/oldGrudge.svg',
  'sensitiveParty?_rule_pic': '/status-icons/sensitiveParty.svg',
  watchAndLearn_rule_pic: '/status-icons/watchAndLearn.svg',
  incorrigible_rule_pic: '/status-icons/incorrigible.svg',
  'berserker!_status_pic': '/status-icons/berserker-.svg',
  berserkerPotioned_status_pic: '/status-icons/berserkerPotioned.svg',
  forestBerserkerPotioned_status_pic: '/status-icons/forestBerserkerPotioned.svg',
  forestPotioned_status_pic: '/status-icons/forestPotioned.svg',
  spiritShelled_status_pic: '/status-icons/spiritShelled.svg',
  shadowWaved_status_pic: '/status-icons/shadowWaved.svg',
  shellUp_status_pic: '/status-icons/shellUp.svg',
  soulSensitive_status_pic: '/status-icons/soulSensitive.svg',
  soulSensitive_p_status_pic: '/status-icons/soulSensitive_p.svg',
  "hunter'sMarked_status_pic": '/status-icons/hunter-sMarked.svg',
  trollRuptured_status_pic: '/status-icons/trollRuptured.svg',
  trollTaunted_status_pic: '/status-icons/trollTaunted.svg',
  trollRuptured_p_status_pic: '/status-icons/trollRuptured_p.svg',
  trollTaunted_p_status_pic: '/status-icons/trollTaunted_p.svg',
  challenge_tidefire_magic: '/status-icons/challenge_tidefire_magic.svg',
  challenge_scattered_opening: '/status-icons/challenge_scattered_opening.svg',
  challenge_coldlight_guard: '/status-icons/challenge_coldlight_guard.svg',
  challenge_wax_order: '/status-icons/challenge_wax_order.svg',
  challenge_tide_order: '/status-icons/challenge_tide_order.svg',
  challenge_tidal_vulnerability: '/status-icons/challenge_tidal_vulnerability.svg',
  challenge_spear_breach: '/status-icons/challenge_spear_breach.svg',
  challenge_troll_regen_mist: '/status-icons/challenge_troll_regen_mist.svg',
  challenge_shield_formation: '/status-icons/challenge_shield_formation.svg',
  challenge_shield_formation_braced: '/status-icons/challenge_shield_formation_braced.svg',
}

export const skillIconMap: Record<SkillId, string> = {
  warrior_t_taunt: '/skill-icons/taunt.svg',
  warrior_t_interrupt: '/skill-icons/interrupt.svg',
  warrior_t_stun: '/skill-icons/stun.svg',
  warrior_t_mass_taunt: '/skill-icons/mass-taunt.svg',
  warrior_t_shield_wall: '/skill-icons/shield-wall.svg',
  warrior_t_cleave: '/skill-icons/cleave.svg',
  warrior_t_burst: '/skill-icons/burst.svg',
  warrior_t_last_stand: '/skill-icons/panic.svg',
  taunt: '/skill-icons/taunt.svg',
  interrupt: '/skill-icons/interrupt.svg',
  stun: '/skill-icons/stun.svg',
  massTaunt: '/skill-icons/mass-taunt.svg',
  shieldWall: '/skill-icons/shield-wall.svg',
  cleave: '/skill-icons/cleave.svg',
  burst: '/skill-icons/burst.svg',
  panic: '/skill-icons/panic.svg',
}

export const lockedSkillIcon = '/skill-icons/locked.svg'
